debug:
  logLevel: info
  flushLevel: trace

frame:
  initDelay: 0
  step: 0
experiment: 0
# This is the impact data set for the footsteps
footstepLForm: "GTS.esp|1C5C7D"
footstepRForm: "GTS.esp|1C5C7D"

# This is the sound descriptor for the footsteps
footstepSoundLForm: "GTS.esp|1E93AB"
footstepSoundRForm: "GTS.esp|1E93AD"
