debug:
  logLevel: info
  flushLevel: trace

frame:
  initDelay: 0
  step: 0

sound:
  # This is the sound descriptor for the footsteps/jumps
  footstepL: "GTS.esp|1E93AB"
  footstepR: "GTS.esp|1E93AD"
  rumbleL: "GTS.esp|36A06D"
  rumbleR: "GTS.esp|36A06D"
  sprintL: "GTS.esp|319060"
  sprintR: "GTS.esp|319060"
  xlFeetL: "GTS.esp|271EF4"
  xlFeetR: "GTS.esp|271EF4"
  jumpLand: "GTS.esp|183F43"

spellEffects:
  # IDs for spell effects
  smallMassiveThreat: "GTS.esp|1A2568"
